.travis.yml

As detailed in https://github.com/travis-ci/dpl/issues/655, the server
that Travis uses to upload packages to PyPI is going to shut down on
July, 3rd. This commit uses an experimental branch provided by Travis
that provides an alternative server.

travis: use edge pypi-legacy branch

---

.travis.yml

As again detailed in https://github.com/travis-ci/dpl/issues/655,
a new version of `dpl` was released that will continue to work
after July, 3rd.

travis: don't use edge pypi-legacy branch

---

inspire_dojson/hep/rules/bd5xx.py
tests/unit/test_dojson_hep_bd5xx.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822627/
Also found and fixed a serious bug: records that were tagged both for CDS and for HAL were being marked as for CDS only.

literature: fix _export_to

---

inspire_dojson/utils/arxiv.py
tests/unit/test_utils_arxiv.py

* Now also handles incorrect capitalizations of arXiv
categories, which occur because legacy is case-insensitive.

utils: normalize arXiv categories better

---

inspire_dojson/utils/arxiv.py
tests/unit/test_utils_arxiv.py

Dashes instead of dots in arXiv categories is a common cause of doJSON failures (~2K records).

utils: more normalization of arXiv categories

---

inspire_dojson/hep/model.py
inspire_dojson/hep/rules/bd9xx.py
tests/unit/test_dojson_hep_bd6xx.py
tests/unit/test_dojson_hep_bd9xx.py

Only records with `980__a:HEP` now get `Literature` as a `_collection`,
records not in HEP don't, in order to properly hide the records not
belonging to the main collection. This requires assigning collections
for the `hep` model based on the contents of the records, instead of
doing it in a filter. Fixes #36.

hep: handle special collections correctly

---

inspire_dojson/common/rules.py
inspire_dojson/hep/__init__.py
inspire_dojson/hep/rules/bdFFT.py
inspire_dojson/utils/__init__.py
setup.py
tests/unit/conftest.py
tests/unit/test_dojson_common.py
tests/unit/test_dojson_hep_bdFFT.py
tests/unit/test_dojson_utils.py

This changes how files (figures and documents) are handled:
* For MARC->JSON conversion, `_fft` is still being written as doJSON
does not have enough information to actually attach the files to the
record, but `urls` now only contains links to external resources.
* In the other direction, `figures` and `documents` are used to prepare
an FFT on legacy.

setup: bump inspire-schemas to version ~43.0

---

inspire_dojson/hep/model.py
tests/unit/test_dojson_hep_bd6xx.py
tests/unit/test_dojson_hep_bd9xx.py
tests/unit/test_dojson_hep_bdFFT.py

Commit 0029b23 forgot to consider that records that we're ingesting from
forms don't yet have the `_collections` key set with the proper value,
so we won't get `980__a:HEP` when sending the record to Legacy.
Note that the existing tests ensure that records that belong to a
special collection only don't become part of the HEP collection, while
records that belonged to both continue belonging to both.
CC: @jmartinm, who reported the bug.

hep: readd ensure_hep

---

inspire_dojson/hep/rules/bdFFT.py
tests/unit/test_dojson_hep_bdFFT.py

Commit 5cb6253 forgot to consider that records we ingest through forms
have the `_fft` key populated, from which an `FFT` field is generated
on legacy.
In the future the form will populate the `documents` key, and this
commit will be reverted.

hep: readd _fft2marc

---

inspire_dojson/utils/text.py
tests/unit/test_dojson_utils.py

Commit da1bd40 removed several unicode encodings and decodings, but
put the last remaining one too late, after the variable had already
been treated as a string (by calling `replace` on it).

utils: convert to unicode earlier

---

inspire_dojson/hep/rules/bd9xx.py
tests/test_hep_bd9xx.py

Following an IRL request by @annetteholtkamp.

hep2marc: output a single m value in references

---

inspire_dojson/hep/rules/bd9xx.py
tests/test_hep_bd9xx.py

Following an IRL request by @annetteholtkamp.

hep2marc: don't add the arxiv prefix to old ids

---

inspire_dojson/hep/rules/bd9xx.py
setup.py
tests/test_hep_bd9xx.py

Expected to fail, as removing `xfail` from a test uncovered a bug that so far had escaped detection.

setup: bump inspire-schemas to version ~46.0

---

inspire_dojson/hep/rules/bd0xx.py
tests/test_hep_bd0xx.py

Previously, `report_numbers` with `source=arXiv` were converted in
`hep2marc` to `037` with `9=arXiv`. This was interpreted on legacy as an
arXiv eprint number, as opposed to an ordinary report number with source
arXiv. This introduces a workaround, converting the `source=arXiv` to
`9=arXiv:reportnumber` instead and doing the opposite in the other
direction.

hep: handle report_numbers with arXiv source

---

inspire_dojson/hep/model.py
tests/test_hep_bd9xx.py
tests/test_hep_model.py

When migrating thousands of records the receiver in invenio-collections
is too slow for practical use. Given that its job is simply to copy
(and normalize) the value of `special_collections` in `_collections`,
we can simply do this work in DoJSON and detach the receiver during
migration (as suggested by @jmartinm).

hep: do the work of invenio-collections in DoJSON

---

inspire_dojson/common/rules.py
inspire_dojson/journals/rules.py
setup.py
tests/test_journals.py
tests/test_processors.py

~~For now this just makes the tests pass, but does not implement any new behavior.~~

journals: bump inspire-schemas to version ~47.0

---

inspire_dojson/institutions/rules.py
tests/test_institutions.py

Previously, due to a bug, the code was ignoring the contents of
`371__g` when determining the `country_code` inside of an address.

institutions: use 371__g when available

---

inspire_dojson/experiments/rules.py
inspire_dojson/institutions/rules.py

This is what I mentioned the other day: perhaps we want to set the flags to `False` only when the data contains an explicit marker of this (like `NONCORE` for the `core` flag), and don't populate it otherwise?

global: set flags to false only explicitly

---

tests/test_hep_bd5xx.py

Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822810/
So this was actually already fixed by https://github.com/inspirehep/inspire-dojson/pull/74, but for some reason Labs didn't have the latest release of `inspire-dojson`. We might as well add an extra test.

tests: add extra test to hep license

---

inspire_dojson/hepnames/model.py
inspire_dojson/hepnames/rules.py
tests/test_hepnames.py

Now that we can assume that a record in the Authors collection has
a `_collections` field we can convert that instead of using a post
processing filter.

hepnames2marc: use _collections, not a filter

---

inspire_dojson/hep/model.py
inspire_dojson/hep/rules/bdFFT.py
inspire_dojson/utils/__init__.py
tests/test_hep_bdFFT.py

Deletes `_fft` field populated from FFT and introduces
`documents` and `figures` instead.
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

hep: populate documents and figures from FFT

---

inspire_dojson/hep/rules/bdFFT.py
tests/test_hep_bdFFT.py

(Closes #109)
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

fix-issue-109: Fix missing `d` subfield error

---

inspire_dojson/hep/model.py

Due to the bug reported in inspirehep/inspire-dojson#114 this method
was never run, and it was pointless as we don't want to derive INSPIRE
categories from the arXiv ones anyway.

hep: remove add_inspire_categories

---

setup.py
tests/test_hep_bd9xx.py

Closes https://github.com/inspirehep/inspire-dojson/pull/118.
Improves all those tests that were wrong because of errors in
understanding the names in references.

tests: benefit from normalize_author_name

---

inspire_dojson/hep/model.py
tests/test_hep_bd7xx.py

A ``publication_info`` that contains only a ``journal_title`` would
like to represent that we know that this paper was submitted to that
journal, but not yet published.
Unfortunately this is inferred from clues like the formatting of the
PDF, not known, and is not later updated if the paper is rejected or
published.
This makes searching on this field more difficult, as it generates
false positives that have to be filtered out at search time.
Therefore this commit moves these values to ``public_notes``.

hep: move incomplete publication_infos

---

inspire_dojson/hep/model.py
inspire_dojson/hep/rules/bd5xx.py
inspire_dojson/hep/rules/bd7xx.py
inspire_dojson/utils/__init__.py
setup.py

Prevents errors like the one fixed in f3de0554 from happening by
adding the ``unicode-string-literal`` dependency, which adds an
extra Flake8 check for Unicode-unsafe constructs.

global: add the unicode-string-literal dependency

---

inspire_dojson/hep/rules/bd1xx.py
tests/test_hep_bd1xx.py

Strips this prefix as it represents some internal bookkeeping done at
Fermilab, which we are not going to support in the future (closes #6).

hep: strip "email:" prefix in the authors key

---

inspire_dojson/hep/rules/bd9xx.py
setup.py
tests/test_hep_bd9xx.py

* In order to stabilize eventually after round-tripping, this requires
to write explicit 999C5z in hep2marc.

hep: preserve legacy_curated in references

---

inspire_dojson/hep/rules/bd1xx.py
tests/test_hep_bd1xx.py

These are `100`/`700`/`701` fields with several `a` subfields, all
sharing the same affiliations. As the different identifiers cannot be
trusted, as it is not known to which author they belong, they are
discarded in this case (closes #68).

hep: handle mashed-up author names

---

inspire_dojson/hep/model.py
tests/test_hep_bd7xx.py

It's not enough to remove a ``publication_info`` when it contains only
a ``journal_title`` as, at XME export time, a ``journal_record`` could
have been added to it. See: 45a859f.

hep: no publication_info even with journal_record

---

setup.py
tests/test_hep_bd9xx.py

One of them was fixed in inspirehep/inspire-utils#32, while the other
was wrong for the reasons explained in inspirehep/inspire-utils#33.

tests: remove xfail from a couple of tests

---

inspire_dojson/hep/rules/bd0xx.py
tests/test_hep_bd0xx.py

@ksachs @tsgit indeed, the problem was in dojson, not in the metadata on labs.

hep2marc: correctly convert pre-2007 arXiv IDs

---

inspire_dojson/common/rules.py
tests/test_common.py

Second commit fixed the bug we noticed the other day (but we should still fix the wrong redirect in `inspire-next`). First commit makes things more uniform.

common: don't produce /api/record

---

inspire_dojson/api.py

The Python interpreter distributed by default with macOS doesn't
support the entire Unicode set, a so-called "narrow build". This
commit uses a different regular expression for detecting invalid
XML characters in that case.

api: support narrow Python builds

---

.travis.yml

Reverts 71c56ce because the timestamp of the last modification
is always going to be after the timestamp saved by pytest-flake8,
since Travis clones a fresh copy of the repository each time it
makes a new build.

travis: avoid caching the pytest-flake8 cache

---

inspire_dojson/hep/rules/bdFFT.py
inspire_dojson/utils/__init__.py
tests/test_hep_bdFFT.py
tests/test_utils.py

* transforms paths to proper `file://` URLs, including escaping.
* makes the AFS base URL configurable through the Flask config.

global: better handle FFT URLs

---

inspire_dojson/utils/__init__.py
tests/test_utils.py

This requires to encode/decode to utf-8 as `urllib.request.pathname2url`
doesn't handle unicode strings.

utils: handle unicode in afs_url

---

.travis.yml
run-tests.sh
setup.py
tests/test_cds.py
tests/test_hep_bd9xx.py

Remove ``pytest-flake8`` and replace it with just ``flake8`` as the
former is sometimes not finding style violations present in the code.

global: don't use pytest-flake8

---

inspire_dojson/data/rules.py
setup.py
tests/test_data.py

Tested locally, only 1 record fails because it has a HDL instead of a DOI: http://inspirehep.net/record/1244560.

data: migrate dois field

---

tests/test_api.py

I was a little paranoid that we still had a bug like the ones fixed in https://github.com/inspirehep/inspire-dojson/commit/29804a9986b85e2c8fa6f76d6fa9f613884d67b4 or https://github.com/inspirehep/inspire-dojson/commit/9b207573c87972b35474ff84ab14db9dde229a30.

tests: add more tests to marcxml2record

---

inspire_dojson/errors.py
inspire_dojson/model.py
tests/test_model.py

This intercepts errors happening inside dojson in order to present them in a more user friendly way:
```
In [1]: from inspire_dojson import marcxml2record
In [2]: marcxml2record('''<record>
...: <datafield tag="980" ind1=" " ind2=" ">
...: <subfield code="a">HEP</subfield>
...: </datafield>
...: <datafield tag="269" ind1=" " ind2=" ">
...: <subfield code="c">Foo</subfield>
...: </datafield>
...: </record>''')
ERROR:root:An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 9))
---------------------------------------------------------------------------
DoJsonError                               Traceback (most recent call last)
<ipython-input-2-1d0482f17771> in <module>()
6 <subfield …
```

698 model: make exceptions more user-friendly

---

.gitignore
inspire_dojson/hep/rules/bdFFT.py
tests/test_hep_bdFFT.py

When generating MARCXML for FFTs populate the name `n` with the value of the key. Otherwise legacy generates the name automatically from the url file name, which leads to issues, as the name is always `content`.
Signed-off-by: Szymon Łopaciuk <szymon@lopaciuk.eu>

hep: add key to FFT__n

---

inspire_dojson/hep/rules/bd5xx.py
tests/test_hep_bd5xx.py

This causes duplication in arXiv licenses in updates as the `preprint` material was not migrated properly.

hep: migrate all license materials

---

inspire_dojson/hep/rules/bd7xx.py
tests/test_hep_bd7xx.py

This is the same as #205 which cannot be reopened because @jacquerie deleted his repo.
We want this in order to avoid having to deal with the ugly #DONE strings in the display formats, and if we ever need them we can go back to the MARC source.

hep: ignore 773__x if marked as done

---

inspire_dojson/cds/model.py
inspire_dojson/conferences/model.py
inspire_dojson/data/model.py
inspire_dojson/experiments/model.py
inspire_dojson/hep/model.py
inspire_dojson/hep/rules/bd7xx.py
inspire_dojson/hepnames/model.py
inspire_dojson/institutions/model.py
inspire_dojson/jobs/model.py
inspire_dojson/journals/model.py
inspire_dojson/model.py
inspire_dojson/utils/__init__.py
tests/test_hep_bd1xx.py

Previously, all lists were being deduped. This is wrong for `authors` that
are allowed to be repeated, and in `record2marcxml` as the json records should be
clean already. This fixes the issue by not deduping in those cases.

global: make dedupe selective

---

inspire_dojson/hep/rules/bd1xx.py
tests/test_hep_bd1xx.py

When removing the deduplication of authors, we inadvertently removed
the deduplication of the author raw affiliations.
Signed-off-by: Salman Maqbool <salman.maqbool@cern.ch>

hep: deduplicate author raw affiliations

---

inspire_dojson/hep/rules/bd1xx.py
tests/test_hep_bd1xx.py

When removing the deduplication of authors, we inadvertently removed
the deduplication of the author ids.
Signed-off-by: Salman Maqbool <salman.maqbool@cern.ch>

hep: deduplicate author ids

---

inspire_dojson/hep/rules/bdFFT.py
tests/test_hep_bdFFT.py
tests/test_utils.py

In case an `FFT` field doesn't contain a `t` subfield, the `lower` function will be called on `None`. Added empty string as default to prevent this.

hep: FFT without t subfield

---

inspire_dojson/hep/rules/bd0xx.py
tests/test_hep_bd0xx.py

If a 037__9 field contains `arxiv` (lower case `x`), then the arXiv identifier will be added to the `report_numbers` field, instead of the `arxiv_eprints` field. With this modification the value will be checked case-insensitively.
Test snippet comes from a package delivered to SCOAP3 by IOP.

hep: arxiv_eprints with lower case arxiv

---

setup.py

INSPIR-643 Remove flask version restriction so that we can use flask 1 on inspirehep and old flask version on inspire-next

Remove flask version restriction

---

inspire_dojson/utils/__init__.py
tests/test_utils.py

`SERVER_NAME` is a always present as a key in `app.app_context()`, but initialized to `None`. Therefore the usual way to define a default does not apply. This patch sets default_server as intended if no SERVER_NAME is defined in the app context.
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>

utils: fix setting of default_server

---

inspire_dojson/hep/model.py
tests/test_hep_model.py

`set_citeable` uses the `is_citeable` function from the
`inspire_schemas` literature builder. That function checks for the
existence of some keys in the `publication_info` to determine whether
the record is citeable. However, all keys in the `publication_info` are
always populated, but the value is `None` in case no value is provided.
This makes `is_citeable` always return true if there is any
`publication_info`.
The solution is to call it after `clean_record` that
strips off keys with `None` values.

hep: correctly set citeable for publication_info

---

inspire_dojson/utils/__init__.py
tests/test_utils.py

* In `absolute_url`, the `PREFERRED_URL_SCHEME` Flask config variable is
now used to determine the scheme to use when making absolute URLs out
of relative ones. This should have the effect of using `https` for
URLs to files in production, avoid unnecessary redirects, and hence
make @tsgit happy.

utils: respect PREFERRED_URL_SCHEME

---

inspire_dojson/api.py

* workaround for
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994998, it turns out
we don't actually need to serialize the XML tree as it will be
deserialized again.

api: add record2marcxml_etree
