inspirehep/inspire-dojson

- README.rst
I mostly want to check if [this line](https://github.com/jacquerie/inspire-dojson/blob/65aaa7d6f4aec90ef371cb613bc8fdcada65917d/.travis.yml#L28) is really doing its job... : )
> docs: add README

- inspire_dojson/utils/__init__.py
- inspire_dojson/utils/text.py
- setup.py
> global: remove dependency on invenio-utils

- inspire_dojson/common/rules.py
- inspire_dojson/hep/model.py
- inspire_dojson/hep/rules/bd0xx.py
- inspire_dojson/hepnames/rules.py
- inspire_dojson/jobs/rules.py
- inspire_dojson/utils/__init__.py
- inspire_dojson/utils/arxiv.py
- tests/unit/test_dojson_hep_bd0xx.py
- tests/unit/test_dojson_hepnames.py
- tests/unit/test_dojson_utils.py
- tests/unit/test_utils_arxiv.py
> Translate arXiv categories and ranks correctly

- .travis.yml
A trivial PR to later test with @david-caro why `autosemver` + automatic push to PyPI is not working.
> travis: small fixes

- setup.py
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> setup: bump inspire-schemas to version ~42.0

- .travis.yml
- inspire_dojson/conferences/model.py
- inspire_dojson/utils/__init__.py
- inspire_dojson/utils/text.py
- setup.py
- tests/unit/test_dojson_hep_bd9xx.py
- tests/unit/test_dojson_hepnames.py
- tests/unit/test_dojson_utils.py
Closes https://github.com/inspirehep/inspire-dojson/issues/17
> global: support Python 3.6

- inspire_dojson/hep/rules/bdFFT.py
- tests/unit/test_dojson_hep_bdFFT.py
> hep: don't require the s subfield in FFT

- inspire_dojson/hep/rules/bd5xx.py
- tests/test_hep_bd5xx.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-nightly-1/group/822160
> hep: squeeze license material into its enum

- inspire_dojson/hep/rules/bd0xx.py
- tests/test_hep_bd0xx.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822798/
> hep: squeeze dois material into its enum

- inspire_dojson/hep/rules/bd7xx.py
- tests/test_hep_bd7xx.py
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs/group/822724/events/152624456/
> hep: handle malformed cnums

- inspire_dojson/hep/model.py
- inspire_dojson/hep/rules/bd5xx.py
- setup.py
- tests/test_hep_bd5xx.py
Closes https://github.com/inspirehep/inspire-dojson/issues/87.
> hep: infer curated flag from 500__a

- inspire_dojson/hep/rules/bd6xx.py
- tests/test_hep_bd6xx.py
Closes https://github.com/inspirehep/inspire-dojson/issues/86.
> hep: migrate information about the accelerator

- inspire_dojson/hep/model.py
- tests/test_hep_model.py
Set it to 'true' by default.
Signed-off-by: David Caro <david@dcaro.es>
> hep: always add curated flag

- inspire_dojson/utils/geo.py
- tests/test_conferences.py
- tests/test_utils_geo.py
> conferences: don't output a postal_address

- inspire_dojson/hep/rules/bd6xx.py
- tests/test_hep_bd6xx.py
Closes https://github.com/inspirehep/inspire-next/issues/2827.
> hep: discard single dashes as acc_experiments

- inspire_dojson/hep/rules/bd6xx.py
- tests/test_hep_bd6xx.py
`keywords` could use a refactor... but not today.
> hep: handle multiple keywords in the same 084

- inspire_dojson/hep/rules/bd5xx.py
Commit a40ee17 missed normalizing the dates in ``thesis_info.date``
and ``_desy_bookkeeping.date``.
> hep: add two missing normalize_date calls

- inspire_dojson/hep/rules/bd0xx.py
- inspire_dojson/hep/rules/bd7xx.py
- setup.py
- tests/test_hep_bd0xx.py
- tests/test_hep_bd7xx.py
> hep: fix handling of ISBNs

- inspire_dojson/hep/rules/bdFFT.py
- tests/test_hep_bdFFT.py
> hep: handle fulltext documents from FFT

- inspire_dojson/hep/model.py
- inspire_dojson/hep/rules/bd0xx.py
- tests/test_hep_bd0xx.py
(closes #32)
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> hep: more robust external_system_identifiers

- inspire_dojson/hep/rules/bd0xx.py
- inspire_dojson/utils/__init__.py
- setup.py
> hep: allow for "editorial note" in material

- setup.py
> setup: bump inspire-schemas to version ~53.0

- inspire_dojson/hep/rules/bd5xx.py
- tests/test_hep_bd0xx.py
- tests/test_hep_bd5xx.py
> hep: take HEPDATA info from 035 instead of 520

- inspire_dojson/hep/rules/bd9xx.py
- tests/test_hep_bd9xx.py
> hep: populate curated_relation in references

- inspire_dojson/hep/rules/bd1xx.py
- tests/test_hep_bd1xx.py
> hep: clean up ORCIDs

- inspire_dojson/common/rules.py
See: https://github.com/inspirehep/inspire-dojson/pull/143#discussion_r151125465
> common: add ECONFPDF to weblinks mapping

- inspire_dojson/hep/model.py
- tests/test_hep_bd5xx.py
In this way, the display priority is directly reflected in the data.
> hep: reorder abstracts to put arXiv last

- inspire_dojson/hep/rules/bd0xx.py
- inspire_dojson/hep/rules/bd5xx.py
- setup.py
- tests/test_hep_bd0xx.py
> hep: move DESY identifiers to _desy_bookkeeping

- inspire_dojson/common/rules.py
- inspire_dojson/hep/rules/bd0xx.py
- setup.py
- tests/test_common.py
- tests/test_hep_bd0xx.py
> setup: bump inspire-schemas to version ~56.0

- inspire_dojson/api.py
- tests/test_api.py
> api: properly serialize in MARC repeated fields

- inspire_dojson/api.py
- tests/test_api.py
> api: support authors in record2marcxml

- inspire_dojson/api.py
- tests/test_api.py
> api: support institutions in marcxml2record

- inspire_dojson/api.py
- inspire_dojson/cds/__init__.py
- inspire_dojson/cds/model.py
- inspire_dojson/cds/rules.py
- inspire_dojson/common/rules.py
- inspire_dojson/hep/model.py
- inspire_dojson/hep/rules/bd5xx.py
- inspire_dojson/hep/rules/bdFFT.py
- inspire_dojson/utils/__init__.py
- setup.py
- tests/test_api.py
- tests/test_cds.py
This also enhances some of the existing rules.
Sem-ver: adds new feature
> api: add conversion from CDS MARC to Literature

- inspire_dojson/hep/rules/bd1xx.py
- tests/test_hep_bd1xx.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/866/
> hep: fix _get_inspire_roles

- inspire_dojson/hep/model.py
- tests/test_hep_bd7xx.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/857/
> hep: fix move_incomplete_publication_infos

- inspire_dojson/common/rules.py
- inspire_dojson/journals/rules.py
- tests/test_hepnames.py
- tests/test_journals.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/868/
> global: fix _private_notes

- inspire_dojson/conferences/rules.py
- tests/test_conferences.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/616/
> conferences: handle unseparated dates

- inspire_dojson/hepnames/rules.py
- tests/test_hepnames.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/413/
> hepnames: discard default name title

- inspire_dojson/hepnames/rules.py
- tests/test_hepnames.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/402/
I'm not 100% sure of this, so I'm not going to merge it. Let's discuss it when we come back to the office (can anybody tell I'm getting bored of Christmas?)
> hepnames: populate value from preferred_name

- inspire_dojson/common/rules.py
- tests/test_common.py
Sentry: https://sentry.inspirehep.net/inspire-sentry/prod/issues/63/
Not 100% of this other one either, so it will have to wait until January (yes, I'm definitely getting bored of Christmas).
> common: make acquisition_source handle dates

- inspire_dojson/api.py
- tests/test_api.py
Closes https://github.com/inspirehep/inspire-dojson/pull/193.
> api: handle multiple as in the same 980

- inspire_dojson/hepnames/rules.py
Just noticed I had these commits lying around...
> hepnames: refactor some rules

- inspire_dojson/cds/rules.py
- tests/test_cds.py
> cds: normalize author names

- inspire_dojson/experiments/rules.py
- inspire_dojson/hep/rules/bd7xx.py
- inspire_dojson/institutions/rules.py
- inspire_dojson/journals/rules.py
- tests/test_experiments.py
- tests/test_hep_bd7xx.py
- tests/test_institutions.py
- tests/test_journals.py
Signed-off-by: Glignos <glignos93@gmail.com>
> implement rule for successor record

- inspire_dojson/hep/rules/bd9xx.py
- tests/test_hep_bd9xx.py
> hep: add external_system_identifier converter

- inspire_dojson/common/rules.py
- tests/test_common.py
Closes https://github.com/inspirehep/inspire-dojson/issues/210, but I'd like to add more tests as 2 in total aren't probably enough.
> common: handle multiple xs in the same 961

- setup.py
See https://nvd.nist.gov/vuln/detail/CVE-2018-1000656
Signed-off-by: David Caro <david@dcaro.es>
> setup: use non-vulnerabe flask

- inspire_dojson/hep/rules/bd9xx.py
- tests/test_hep_bd9xx.py
Signed-off-by: David Caro <david@dcaro.es>
> references.url: avoid duplicates

- inspire_dojson/hepnames/rules.py
- tests/test_hepnames.py
Addresses @hoc3426's comment in https://github.com/inspirehep/inspire-dojson/commit/62423fdc8222ad56e69c50a409dbd8f3d2d5758e#commitcomment-30537170.
> hepnames: migrate advisor ORCIDs

- inspire_dojson/hepnames/rules.py
- tests/test_hepnames.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> hepnames: fix positions default value for ``current``

- inspire_dojson/hep/rules/bd9xx.py
- tests/test_hep_bd9xx.py
@ksachs this fixes the issue you pointed out by email.
> hep: correctly handle repeated 999C5z

- inspire_dojson/hep/rules/bd9xx.py
- tests/test_hep_bd9xx.py
> hep: handle deleted from 980__a

- inspire_dojson/hep/rules/bd9xx.py
> hep: recognize SLAC in _collections

- inspire_dojson/common/rules.py
- inspire_dojson/hep/rules/bd0xx.py
- inspire_dojson/hep/rules/bd1xx.py
- inspire_dojson/hep/rules/bdFFT.py
- inspire_dojson/hepnames/rules.py
- inspire_dojson/jobs/rules.py
- tests/test_hep_bdFFT.py
> dojson: change invalid escape sequences

- inspire_dojson/hep/rules/bd1xx.py
- setup.py
- tests/test_hep_bd1xx.py
Following this addition to the schemas: https://github.com/inspirehep/inspire-schemas/commit/9cdfc332a611a51d9ae96c4db6ab364155778070
> hep: convert from/to affiliation_identifiers

- inspire_dojson/cds/rules.py
- tests/test_cds.py
> cds: ignore Not Applicable field in 693__

- inspire_dojson/cds/rules.py
- tests/test_cds.py
> cds: escape spaces in urls

- inspire_dojson/cds/rules.py
- tests/test_cds.py
> cds: accept 037__z as report number value

- inspire_dojson/cds/rules.py
- tests/test_cds.py
> cds: handle urls with special characters

- inspire_dojson/common/rules.py
- inspire_dojson/jobs/rules.py
- tests/test_jobs.py
> jobs: correctly handle deleted records

- inspire_dojson/utils/__init__.py
- tests/test_utils.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> utils: add option for labs afs http service

- inspire_dojson/api.py
- inspire_dojson/errors.py
- inspire_dojson/utils/__init__.py
- tests/test_api.py
* INSPIR-2896
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.comk>
> jobs: raise NotSupportedError on migration

- inspire_dojson/hep/rules/bd9xx.py
- setup.py
- tests/test_hep_bd9xx.py
> hep: handle additional pubnotes

- inspire_dojson/hep/rules/bd1xx.py
- tests/test_hep_bd1xx.py
> hep: remove trailing commas and spaces from author full name

- inspire_dojson/utils/geo.py
- tests/test_conferences.py
- tests/test_utils_geo.py
> conferences: improve address parsing

- inspire_dojson/hep/rules/bdFFT.py
- tests/test_hep_bdFFT.py
> hep: hide documents with source arxiv

- inspire_dojson/hep/rules/bdFFT.py
- tests/test_hep_bdFFT.py
> hep: recognize plots with composite extension

- inspire_dojson/hep/rules/bdFFT.py
- inspire_dojson/utils/__init__.py
- tests/test_hep_bdFFT.py
- tests/test_utils.py
> hep2marc: convert AFS URLs to paths

- inspire_dojson/hep/rules/bdFFT.py
- tests/test_hep_bdFFT.py
> hep2marc: use filename in FFT

- inspire_dojson/experiments/rules.py
- tests/test_experiments.py
> experiments: add inspire_classification instead of class number

- inspire_dojson/hep/rules/bdFFT.py
- setup.py
- tests/test_hep_bdFFT.py
ref inspirehep/inspirehep#1120
> Remove hidden flag from arxiv PDFs

- inspire_dojson/hep/rules/bdFFT.py
- tests/test_hep_bdFFT.py
This reverts commit 145dae168307aabf1635c6cf64588f1310fc3951.
> Revert "Remove hidden flag from arxiv PDFs"

- inspire_dojson/cds/rules.py
- tests/test_cds.py
* ref inspirehep/inspirehep#1344
> CDS: improve handling of accelerators

- inspire_dojson/hep/model.py
- tests/test_hep_bd7xx.py
- tests/test_hep_bdFFT.py
* ref inspirehep/inspirehep#1533.
> hep: don't create "submitted to None" notes

- inspire_dojson/hep/rules/bd9xx.py
- tests/test_hep_bd9xx.py
* ref inspirehep/inspirehep#1550
> hep: treat references with only $$0 as curated

- inspire_dojson/hepnames/rules.py
- tests/test_hepnames.py
* Adds `hidden` field to `advisors`, `positions` and `projects`.
> hepnames: addition of `hidden` field

- inspire_dojson/hep/rules/bd2xx.py
- setup.py
- tests/test_hep_bd2xx.py
* Ref inspirehep/inspirehep#1649.
Sem-ver: new feature
> hep: handle rpp flag

- inspire_dojson/experiments/rules.py
- tests/test_experiments.py
* ref inspirehep/inspirehep#1800
> experiments: handle subgroup names

- inspire_dojson/hepnames/rules.py
- tests/test_hepnames.py
* refs inspirehep/inspirehep#1832.
> hepnames: convert deprecated identifiers

- inspire_dojson/hep/rules/bd6xx.py
- tests/test_hep_bd6xx.py
* related to inspirehep/inspirehep#1677.
> hep: handle automatic keywords

- .github/workflows/pull-request.yml
- .github/workflows/push-master.yml
- .github/workflows/test.yml
* ref https://github.com/cern-sis/issues-inspire/issues/859
> gh-actions: adapt pipelines

- .github/workflows/test-python-3.yml
- Dockerfile.py2
- README.rst
- setup.py
* ref https://github.com/cern-sis/issues-inspire/issues/916
> setup: python 3.11 fix
